export default function Float(){
    return (
        <div id="wd-float-divs">
            <h2>Float</h2>
            <div>
                <img className="wd-float-right"
                    src="https://www.staradvertiser.com/wp-content/uploads/2021/08/web1_Starship-gap2.jpg"/>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum pellentesque ultricies urna, ac dignissim mi blandit quis. Nulla facilisi. Maecenas volutpat tristique sem, eu porta lectus consequat at. Nulla facilisi. In a mattis ligula, a tristique felis. Integer in magna leo. In enim mi, molestie accumsan libero in, fermentum dictum odio. Cras vel massa eu arcu ultrices aliquam et a enim. Aliquam diam ante, sagittis et mauris sed, cursus mollis est. Nulla facilisi. Vestibulum nec lacus id augue dapibus congue. Mauris sodales ornare ante, eget consectetur mauris cursus id. Duis fermentum arcu nec risus lobortis ullamcorper. Praesent ultricies ante vel justo gravida gravida. Nunc nec efficitur ligula, eu pulvinar enim. Ut ultricies vestibulum nisl, vel finibus lorem vestibulum tincidunt.
                Pellentesque porta tincidunt quam, nec gravida lorem egestas at. Aenean sit amet malesuada enim. Nullam augue ipsum, blandit vel risus sit amet, varius imperdiet justo. Maecenas vitae aliquam lectus, ac imperdiet nisl. Pellentesque sed enim vel erat accumsan ornare sit amet et risus. Nunc eget magna auctor, euismod nibh sed, bibendum libero. Fusce dolor erat, imperdiet id nibh a, fringilla fermentum tortor.
                Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed maximus molestie justo sed rhoncus. Aenean imperdiet pulvinar risus eget convallis. Donec vel tincidunt mi. Aenean sed pulvinar lectus, accumsan auctor magna. Sed facilisis enim in tellus accumsan, quis pretium erat dictum. In posuere, tellus ut lobortis accumsan, est sapien sodales lacus, a placerat urna risus sed arcu. Praesent fermentum dolor id nisi eleifend facilisis. In non massa vitae nisl ullamcorper rhoncus vitae eget ex. Suspendisse vitae neque eget augue semper tincidunt. Nunc aliquam est ut sollicitudin venenatis. Praesent tincidunt arcu nec ipsum blandit, eget sollicitudin magna commodo.
                Vestibulum nec luctus justo. Integer vestibulum pulvinar lacus sed imperdiet. Donec ac augue vitae metus rhoncus gravida. Cras condimentum urna elit, sit amet consectetur lorem dictum ultricies. Sed convallis malesuada sapien, ut auctor eros tempor a. Praesent et bibendum massa, sit amet pharetra nibh. Phasellus rhoncus, augue quis lobortis imperdiet, dui lectus sagittis tellus, quis eleifend urna nunc gravida augue.
                Nullam vitae sapien nec risus finibus suscipit. Proin tristique vulputate venenatis. Fusce cursus, arcu nec consectetur pharetra, leo odio blandit enim, non tempus arcu purus ac magna. Mauris ultrices tellus a nibh accumsan finibus. Nunc finibus fringilla pellentesque. Proin interdum sagittis justo, ac porta elit sodales sed. Mauris auctor posuere libero, interdum rutrum nulla. Donec non tellus nisl. Aenean in justo commodo, ultricies odio id, commodo nisl. Suspendisse vel mauris sed eros vestibulum dapibus non non odio.
                <img className="wd-float-left"
                    src="https://www.staradvertiser.com/wp-content/uploads/2021/08/web1_Starship-gap2.jpg"/>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum pellentesque ultricies urna, ac dignissim mi blandit quis. Nulla facilisi. Maecenas volutpat tristique sem, eu porta lectus consequat at. Nulla facilisi. In a mattis ligula, a tristique felis. Integer in magna leo. In enim mi, molestie accumsan libero in, fermentum dictum odio. Cras vel massa eu arcu ultrices aliquam et a enim. Aliquam diam ante, sagittis et mauris sed, cursus mollis est. Nulla facilisi. Vestibulum nec lacus id augue dapibus congue. Mauris sodales ornare ante, eget consectetur mauris cursus id. Duis fermentum arcu nec risus lobortis ullamcorper. Praesent ultricies ante vel justo gravida gravida. Nunc nec efficitur ligula, eu pulvinar enim. Ut ultricies vestibulum nisl, vel finibus lorem vestibulum tincidunt.
                Pellentesque porta tincidunt quam, nec gravida lorem egestas at. Aenean sit amet malesuada enim. Nullam augue ipsum, blandit vel risus sit amet, varius imperdiet justo. Maecenas vitae aliquam lectus, ac imperdiet nisl. Pellentesque sed enim vel erat accumsan ornare sit amet et risus. Nunc eget magna auctor, euismod nibh sed, bibendum libero. Fusce dolor erat, imperdiet id nibh a, fringilla fermentum tortor.
                Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed maximus molestie justo sed rhoncus. Aenean imperdiet pulvinar risus eget convallis. Donec vel tincidunt mi. Aenean sed pulvinar lectus, accumsan auctor magna. Sed facilisis enim in tellus accumsan, quis pretium erat dictum. In posuere, tellus ut lobortis accumsan, est sapien sodales lacus, a placerat urna risus sed arcu. Praesent fermentum dolor id nisi eleifend facilisis. In non massa vitae nisl ullamcorper rhoncus vitae eget ex. Suspendisse vitae neque eget augue semper tincidunt. Nunc aliquam est ut sollicitudin venenatis. Praesent tincidunt arcu nec ipsum blandit, eget sollicitudin magna commodo.
                Vestibulum nec luctus justo. Integer vestibulum pulvinar lacus sed imperdiet. Donec ac augue vitae metus rhoncus gravida. Cras condimentum urna elit, sit amet consectetur lorem dictum ultricies. Sed convallis malesuada sapien, ut auctor eros tempor a. Praesent et bibendum massa, sit amet pharetra nibh. Phasellus rhoncus, augue quis lobortis imperdiet, dui lectus sagittis tellus, quis eleifend urna nunc gravida augue.
                Nullam vitae sapien nec risus finibus suscipit. Proin tristique vulputate venenatis. Fusce cursus, arcu nec consectetur pharetra, leo odio blandit enim, non tempus arcu purus ac magna. Mauris ultrices tellus a nibh accumsan finibus. Nunc finibus fringilla pellentesque. Proin interdum sagittis justo, ac porta elit sodales sed. Mauris auctor posuere libero, interdum rutrum nulla. Donec non tellus nisl. Aenean in justo commodo, ultricies odio id, commodo nisl. Suspendisse vel mauris sed eros vestibulum dapibus non non odio.
                <img className="wd-float-right"
                    src="https://www.staradvertiser.com/wp-content/uploads/2021/08/web1_Starship-gap2.jpg"/>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum pellentesque ultricies urna, ac dignissim mi blandit quis. Nulla facilisi. Maecenas volutpat tristique sem, eu porta lectus consequat at. Nulla facilisi. In a mattis ligula, a tristique felis. Integer in magna leo. In enim mi, molestie accumsan libero in, fermentum dictum odio. Cras vel massa eu arcu ultrices aliquam et a enim. Aliquam diam ante, sagittis et mauris sed, cursus mollis est. Nulla facilisi. Vestibulum nec lacus id augue dapibus congue. Mauris sodales ornare ante, eget consectetur mauris cursus id. Duis fermentum arcu nec risus lobortis ullamcorper. Praesent ultricies ante vel justo gravida gravida. Nunc nec efficitur ligula, eu pulvinar enim. Ut ultricies vestibulum nisl, vel finibus lorem vestibulum tincidunt.
                Pellentesque porta tincidunt quam, nec gravida lorem egestas at. Aenean sit amet malesuada enim. Nullam augue ipsum, blandit vel risus sit amet, varius imperdiet justo. Maecenas vitae aliquam lectus, ac imperdiet nisl. Pellentesque sed enim vel erat accumsan ornare sit amet et risus. Nunc eget magna auctor, euismod nibh sed, bibendum libero. Fusce dolor erat, imperdiet id nibh a, fringilla fermentum tortor.
                Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed maximus molestie justo sed rhoncus. Aenean imperdiet pulvinar risus eget convallis. Donec vel tincidunt mi. Aenean sed pulvinar lectus, accumsan auctor magna. Sed facilisis enim in tellus accumsan, quis pretium erat dictum. In posuere, tellus ut lobortis accumsan, est sapien sodales lacus, a placerat urna risus sed arcu. Praesent fermentum dolor id nisi eleifend facilisis. In non massa vitae nisl ullamcorper rhoncus vitae eget ex. Suspendisse vitae neque eget augue semper tincidunt. Nunc aliquam est ut sollicitudin venenatis. Praesent tincidunt arcu nec ipsum blandit, eget sollicitudin magna commodo.
                Vestibulum nec luctus justo. Integer vestibulum pulvinar lacus sed imperdiet. Donec ac augue vitae metus rhoncus gravida. Cras condimentum urna elit, sit amet consectetur lorem dictum ultricies. Sed convallis malesuada sapien, ut auctor eros tempor a. Praesent et bibendum massa, sit amet pharetra nibh. Phasellus rhoncus, augue quis lobortis imperdiet, dui lectus sagittis tellus, quis eleifend urna nunc gravida augue.
                Nullam vitae sapien nec risus finibus suscipit. Proin tristique vulputate venenatis. Fusce cursus, arcu nec consectetur pharetra, leo odio blandit enim, non tempus arcu purus ac magna. Mauris ultrices tellus a nibh accumsan finibus. Nunc finibus fringilla pellentesque. Proin interdum sagittis justo, ac porta elit sodales sed. Mauris auctor posuere libero, interdum rutrum nulla. Donec non tellus nisl. Aenean in justo commodo, ultricies odio id, commodo nisl. Suspendisse vel mauris sed eros vestibulum dapibus non non odio.
                <img className="wd-float-left"
                    src="https://www.staradvertiser.com/wp-content/uploads/2021/08/web1_Starship-gap2.jpg"/>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum pellentesque ultricies urna, ac dignissim mi blandit quis. Nulla facilisi. Maecenas volutpat tristique sem, eu porta lectus consequat at. Nulla facilisi. In a mattis ligula, a tristique felis. Integer in magna leo. In enim mi, molestie accumsan libero in, fermentum dictum odio. Cras vel massa eu arcu ultrices aliquam et a enim. Aliquam diam ante, sagittis et mauris sed, cursus mollis est. Nulla facilisi. Vestibulum nec lacus id augue dapibus congue. Mauris sodales ornare ante, eget consectetur mauris cursus id. Duis fermentum arcu nec risus lobortis ullamcorper. Praesent ultricies ante vel justo gravida gravida. Nunc nec efficitur ligula, eu pulvinar enim. Ut ultricies vestibulum nisl, vel finibus lorem vestibulum tincidunt.
                Pellentesque porta tincidunt quam, nec gravida lorem egestas at. Aenean sit amet malesuada enim. Nullam augue ipsum, blandit vel risus sit amet, varius imperdiet justo. Maecenas vitae aliquam lectus, ac imperdiet nisl. Pellentesque sed enim vel erat accumsan ornare sit amet et risus. Nunc eget magna auctor, euismod nibh sed, bibendum libero. Fusce dolor erat, imperdiet id nibh a, fringilla fermentum tortor.
                Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed maximus molestie justo sed rhoncus. Aenean imperdiet pulvinar risus eget convallis. Donec vel tincidunt mi. Aenean sed pulvinar lectus, accumsan auctor magna. Sed facilisis enim in tellus accumsan, quis pretium erat dictum. In posuere, tellus ut lobortis accumsan, est sapien sodales lacus, a placerat urna risus sed arcu. Praesent fermentum dolor id nisi eleifend facilisis. In non massa vitae nisl ullamcorper rhoncus vitae eget ex. Suspendisse vitae neque eget augue semper tincidunt. Nunc aliquam est ut sollicitudin venenatis. Praesent tincidunt arcu nec ipsum blandit, eget sollicitudin magna commodo.
                Vestibulum nec luctus justo. Integer vestibulum pulvinar lacus sed imperdiet. Donec ac augue vitae metus rhoncus gravida. Cras condimentum urna elit, sit amet consectetur lorem dictum ultricies. Sed convallis malesuada sapien, ut auctor eros tempor a. Praesent et bibendum massa, sit amet pharetra nibh. Phasellus rhoncus, augue quis lobortis imperdiet, dui lectus sagittis tellus, quis eleifend urna nunc gravida augue.
                Nullam vitae sapien nec risus finibus suscipit. Proin tristique vulputate venenatis. Fusce cursus, arcu nec consectetur pharetra, leo odio blandit enim, non tempus arcu purus ac magna. Mauris ultrices tellus a nibh accumsan finibus. Nunc finibus fringilla pellentesque. Proin interdum sagittis justo, ac porta elit sodales sed. Mauris auctor posuere libero, interdum rutrum nulla. Donec non tellus nisl. Aenean in justo commodo, ultricies odio id, commodo nisl. Suspendisse vel mauris sed eros vestibulum dapibus non non odio.
                <div className="wd-float-done"></div>
            </div>



            <div>
                <div className="wd-float-left wd-dimension-portrait wd-bg-color-yellow">
                    Yellow </div>
                <div className="wd-float-left wd-dimension-portrait wd-bg-color-blue wd-fg-color-white">
                    Blue </div>
                <div className="wd-float-left wd-dimension-portrait wd-bg-color-red">
                    Red </div>
                <img className="wd-float-right"
                    src="https://www.staradvertiser.com/wp-content/uploads/2021/08/web1_Starship-gap2.jpg"/>
                <div className="wd-float-done"></div>
            </div>
        </div>
    );
}